CREATE TABLE IF NOT EXISTS posts (
    post_code INT NOT NULL,
    post_name VARCHAR(255) NOT NULL,
    post_address VARCHAR(255) NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (post_code),
    CONSTRAINT uk_posts_post_code UNIQUE (post_code)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_type VARCHAR(50) NOT NULL,
    post_code INT NOT NULL,
    receiver_address VARCHAR(255) NOT NULL,
    receiver_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (item_id),
    CONSTRAINT fk_items_post_code_to_posts FOREIGN KEY (post_code) REFERENCES posts(post_code) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movement (
    movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT NOT NULL,
    post_code BIGINT NOT NULL,
    move_type VARCHAR(50) NOT NULL,
    move_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_movements PRIMARY KEY (movement_id),
    CONSTRAINT uc_movement_item_id_post_code UNIQUE (item_id, post_code),
    CONSTRAINT FK_MOVEMENTS_ON_ITEM_ID FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT FK_MOVEMENTS_ON_POST_CODE FOREIGN KEY (post_code) REFERENCES posts (post_code) ON DELETE CASCADE
)
